### ISSUE TITLE
Occasional java.lang.NoClassDefFoundError for compiles proxy classes

### ISSUE THREAD

**Issue by pz07** [kostaskougios/mapperdao#11]
It looks like a code initializing proxy classes cache is not thread safe. Occasionally I get this exception: 
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.package.MyClass_$2
        at sun.reflect.GeneratedSerializationConstructorAccessor57.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:56)
        at com.googlecode.mapperdao.lazyload.LazyLoadManager.proxyFor(LazyLoadManager.scala:63)
        at com.googlecode.mapperdao.jdbc.impl.MapperDaoImpl.lazyLoadEntity(MapperDaoImpl.scala:338)
        at com.googlecode.mapperdao.jdbc.impl.MapperDaoImpl.$anonfun$toEntities$5(MapperDaoImpl.scala:301)
        at com.googlecode.mapperdao.internal.EntityMap.$anonfun$get$1(EntityMap.scala:46)

```
It looks like codeCache map contains an entry for a class that is not compiled or not available to the current class loader. It doesn't happen all the time and it seems to be quite random. 

The code seems to be thread safe to me, but there's something wrong there definitely. Am I missing something? Any idea what could cause this exception?

**Comment by kostaskougios** [comment]
The code seems thread safe to me too. My guess at the moment is that the instantiator was created on a different classloader than the classloader during the failing call.
		val instantiator = objenesis.getInstantiatorOf(proxyClz)
objenesis seems to cache it. Is there a way to say print the classloader when this occurs or maybe create a simple test case with the issue?

**Comment by pz07** [comment]
I finally found the root cause. The class loader is not an issue in this case. 
It's a concurrency issue, indeed, but not in the class I initially suspected (LazyLoadManager). The problem is in com.googlecode.classgenerator.runtime.MImpl
What's wrong here is that get method is not thread safe (remove method of scala.collection.mutable.Map; updated can be lost due to invoking this method while appending other items). 
Also, codeCache is local to the class loader, but this object is global. There are multiple LazyLoadManagers in my project, which means that multiple proxy classes can be generated at the same time. 

The error happens in initialization phase of proxy class: 
```
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at com.googlecode.classgenerator.runtime.MImpl$.get(MImpl.scala:18)
	at com.googlecode.classgenerator.runtime.MImpl.get(MImpl.scala)
	at com.peerius.products.model.Category_$749.<clinit>(Category_$749.java)
	... 23 more
```

ClassBuilder: 
```
field(
				"""
					private static Class[] __M$_ARGS%d = MImpl.get(%d);
				""".format(methodCounter, methodCounter))
```

The easiest way to fix it would be to make MImpl thread safe by synchronization or using thread safe map. 

Why think though I don't understand is why do you need to make method names unique by adding the counter? Surely, method names doesn't have to be unique globally. Every proxy class can have the same set of methods. This would eliminate the need of having MImpl completely. Am I missing something?

**Comment by kostaskougios** [comment]
Deployed 1.0.4 for scala 2.12
